import os
path = os.path.join(os.getcwd(), "src/components/admin/AdminFull.svelte")
nl = chr(10)
dq = chr(34)
sq = chr(39)
lt = chr(60)
gt = chr(62)
dl = chr(36)
co = chr(58)
lb = chr(123)
rb = chr(125)

L = []
a = L.append
# SCRIPT SECTION
a(lt + "script lang=" + dq + "ts" + dq + gt)
a("  import { getNavConfig, setNavConfig, cloneLinks, genId, addChild, removeChild, moveItem, updateItem, deleteItem, findItem } from @/utils/navMenuConfig;")
a("  import type { NavMenuItem } from @/types/navMenuConfig;")
a("  import { defaultNavItems } from @/types/navMenuConfig;")
a("")
a("  interface ConfigData { [key: string]: any; }")
a("  interface AllConfigs { [key: string]: any; }")
a("")
a("  let configs = {};")
a("  let activeTab = @"site@";")
a("  let saving = false;")
a("  let saveStatus = @"@";")
a("  let githubToken = @"@";")
a("  let githubRepo = @"@";")
a("  let editData = {};")
a("")
a("  const tabs = [")
a("    { id: @"site@", label: @"网站信息@", icon: @"material-symbols:home@" },")
a("    { id: @"nav@", label: @"导航栏@", icon: @"material-symbols:menu@" },")
a("    { id: @"effects@", label: @"特效控制@", icon: @"material-symbols:auto-fix-high@" },")
a("    { id: @"wallpaper@", label: @"壁纸设置@", icon: @"material-symbols:wallpaper@" },")
a("    { id: @"music@", label: @"音乐播放器@", icon: @"material-symbols:music-note@" },")
a("    { id: @"comment@", label: @"评论系统@", icon: @"material-symbols:chat@" },")
a("    { id: @"profile@", label: @"个人资料@", icon: @"material-symbols:person@" },")
a("    { id: @"sidebar@", label: @"侧边栏@", icon: @"material-symbols:sidebar@" },")
a("    { id: @"font@", label: @"字体设置@", icon: @"material-symbols:font-download@" },")
a("    { id: @"pio@", label: @"看板娘@", icon: @"material-symbols:toys@" },")
a("    { id: @"announcement@", label: @"公告设置@", icon: @"material-symbols:campaign@" },")
a("    { id: @"portfolio@", label: @"开屏动画@", icon: @"material-symbols:animation@" },")
a("    { id: @"analytics@", label: @"数据分析@", icon: @"material-symbols:insights@" },")
a("    { id: @"license@", label: @"许可证@", icon: @"material-symbols:verified@" },")
a("    { id: @"cover@", label: @"封面图@", icon: @"material-symbols:image@" },")
a("    { id: @"sponsor@", label: @"打赏设置@", icon: @"material-symbols:favorite@" },")
a("  ];")
a("")